#!/bin/sh -e
doit() {
	echo "* $1"
	../ldapvi --diff $1.a $1.b >$1.out || echo FAILED
	if test -f $1.wanted; then
		diff -u $1.wanted $1.out || echo FAILED
	else
		echo creating $1.wanted
		mv $1.out $1.wanted
		cat $1.wanted
	fi
}

if test x$1 = x; then
	ls -1 ???.a | cut -d. -f1 | while read t; do doit $t; done
else
	doit $1
fi
